package com.doniapr.moviecatalogue.utils

import com.doniapr.moviecatalogue.data.source.local.entity.Movie
import com.doniapr.moviecatalogue.data.source.local.entity.TvShow

object Content {
    val movies = arrayOf(
        Movie(
            "531876",
            "The Outpost",
            "A small unit of U.S. soldiers, alone at the remote Combat Outpost Keating, located deep in the valley of three mountains in Afghanistan, battles to defend against an overwhelming force of Taliban fighters in a coordinated attack. The Battle of Kamdesh, as it was known, was the bloodiest American engagement of the Afghan War in 2009 and Bravo Troop 3-61 CAV became one of the most decorated units of the 19-year conflict.",
            "The Outpost",
            "Action, Drama, History, War",
            "2020-06-24",
            "123",
            "The mission was survival.",
            "Released",
            "7",
            "73",
            "/goEW6QqoFxNI2pfbpVqmXj2WXwd.jpg",
            "/n1RohH2VoK1CdVI2fXvcP19dSlm.jpg"
        ),
        Movie(
            "475430",
            "Artemis Fowl",
            "Artemis Fowl is a 12-year-old genius and descendant of a long line of criminal masterminds. He soon finds himself in an epic battle against a race of powerful underground fairies who may be behind his father's disappearance.",
            "Artemis Fowl",
            "Adventure, Fantasy, Science Fiction, Family",
            "2020-06-12",
            "95",
            "Remember the name",
            "Released",
            "5.9",
            "604",
            "/tI8ocADh22GtQFV28vGHaBZVb0U.jpg",
            "/o0F8xAt8YuEm5mEZviX5pEFC12y.jpg"
        ),
        Movie(
            id= "706510",
            title= "Desperados",
            overview="A panicked young woman and her two best friends fly to Mexico to delete a ranting email she sent to her new boyfriend. On arrival, they run into her former beau, who soon gets caught up in their frantic scheme.",
            originalTitle= "Desperados",
            genres="Comedy, Romance",
            releaseDate= "2020-07-03",
            runtime = "105",
            tagline = "",
            status = "Released",
            voteAverage= "6.5",
            voteCount= "137",
            posterPath= "/hoUzSMxGu4Bm73EvH6B3iceFwW8.jpg",
            backdropPath= "/k8H6Qp4uJ9WHArPQwDqCaW9g3Sj.jpg"
        ),
        Movie(
            id="516486",
            title= "Greyhound",
            overview= "A first-time captain leads a convoy of allied ships carrying thousands of soldiers across the treacherous waters of the “Black Pit” to the front lines of WW2. With no air cover protection for 5 days, the captain and his convoy must battle the surrounding enemy Nazi U-boats in order to give the allies a chance to win the war.",
            originalTitle= "Greyhound",
            genres= "War, Action, Drama",
            releaseDate= "2020-07-10",
            runtime="91",
            tagline= "The only thing more dangerous than the front lines was the fight to get there.",
            status= "Released",
            voteAverage="6.1",
            voteCount ="39",
            posterPath= "/AsdB9A2XGalCZVjlyG9tRf03IfW.jpg",
            backdropPath= "/xXBnM6uSTk6qqCf0SRZKXcga9Ba.jpg"
        ),
        Movie(
            id= "385103",
            title= "Scoob!",
            overview= "In Scooby-Doo’s greatest adventure yet, see the never-before told story of how lifelong friends Scooby and Shaggy first met and how they joined forces with young detectives Fred, Velma, and Daphne to form the famous Mystery Inc. Now, with hundreds of cases solved, Scooby and the gang face their biggest, toughest mystery ever: an evil plot to unleash the ghost dog Cerberus upon the world. As they race to stop this global “dogpocalypse,” the gang discovers that Scooby has a secret legacy and an epic destiny greater than anyone ever imagined.",
            originalTitle= "Scoob!",
            genres= "Family, Animation, Comedy, Mystery, Adventure",
            releaseDate= "2020-05-15",
            runtime= "94",
            tagline= "Mystery loves company.",
            status= "Released",
            voteAverage= "8.0",
            voteCount= "1191",
            posterPath= "/jHo2M1OiH9Re33jYtUQdfzPeUkx.jpg",
            backdropPath ="/fKtYXUhX5fxMxzQfyUcQW9Shik6.jpg"
        ),
        Movie(
            id= "529149",
            title= "Darlin'",
            overview= "Found at a Catholic hospital filthy and ferocious, feral teenager Darlin’ is whisked off to a care home run by The Bishop and his obedient nuns, where she’s to be rehabilitated into a \"good girl\" as an example of the miraculous work of the church. But Darlin’ holds a secret darker than the \"sins\" she is threatened with, and she is not traveling alone. The Woman who raised her, equally fierce and feral, is ever present in the shadows of Darlin’s psyche and is determined to come for her no matter who tries to get in her way.",
            originalTitle= "Darlin'",
            genres= "Horror, Mystery",
            releaseDate= "2020-07-10",
            runtime= "101",
            status= "Released",
            tagline= "Don't mess with mother's nature.",
            voteAverage= "4.3",
            voteCount= "3",
            posterPath= "/hnNjlXAQan8WdNtQMfdldAGoqMF.jpg",
            backdropPath= "/A47BxbWFfQAKvVsZwiMuuF34s9R.jpg"
        ),
        Movie(
            id= "531454",
            title="Eurovision Song Contest: The Story of Fire Saga",
            overview= "Two small-town aspiring musicians chase their pop star dreams at a global music competition, where high stakes, scheming rivals and onstage mishaps test their bond.",
            originalTitle= "Eurovision Song Contest: The Story of Fire Saga",
            genres= "Comedy, Music",
            releaseDate= "2020-06-26",
            runtime= "124",
            tagline= "Nobody wins solo",
            status= "Released",
            voteAverage= "6.5",
            voteCount= "348",
            posterPath= "/9zrbgYyFvwH8sy5mv9eT25xsAzL.jpg",
            backdropPath="/jMO1icztaUUEUApdAQx0cZOt7b8.jpg"
        ),
        Movie(
            id="508439",
            title= "Onward",
            overview= "In a suburban fantasy world, two teenage elf brothers embark on an extraordinary quest to discover if there is still a little magic left out there.",
            originalTitle= "Onward",
            genres= "Animation, Family, Adventure, Comedy, Fantasy",
            releaseDate= "2020-02-29",
            runtime="102",
            tagline= "Their quest begineth.",
            status= "Released",
            voteAverage= "7.9",
            voteCount= "2495",
            posterPath= "/f4aul3FyD3jv3v4bul1IrkWZvzq.jpg",
            backdropPath= "/xFxk4vnirOtUxpOEWgA1MCRfy6J.jpg"
        ),
        Movie(
            id= "429422",
            title= "Capone",
            overview= "The 47-year old Al Capone, after 10 years in prison, starts suffering from dementia and comes to be haunted by his violent past.",
            originalTitle= "Capone",
            genres= "Crime, Drama",
            releaseDate= "2020-07-10",
            runtime= "103",
            tagline= "We all pay for our crimes in the end.",
            status= "Released",
            voteAverage= "4.8",
            voteCount= "6",
            posterPath= "/75gDv38UgRtAukSxNXcjatyQmEa.jpg",
            backdropPath= "/8YpXQS3zo25ZexQVkQyhsLlzINB.jpg"
        ),
        Movie(
            id= "619592",
            title= "Force of Nature",
            overview= "A gang of thieves plan a heist during a hurricane and encounter trouble when a disgraced cop tries to force everyone in the building to evacuate.",
            originalTitle= "Force of Nature",
            genres= "Action, Drama",
            releaseDate= "2020-07-02",
            runtime= "91",
            tagline= "",
            status= "Released",
            voteAverage= "5.6",
            voteCount= "59",
            posterPath= "/ucktgbaMSaETUDLUBp1ubGD6aNj.jpg",
            backdropPath= "/eIqyISB5j99OSRZUuvdN9g2bBsS.jpg"
        ),
        Movie(
            id= "717514",
            title= "Parallax",
            overview= "A young artist wakes up in a life that she doesn't recognize, spending her time asleep haunted by nightmares of drowning in a black abysmal void. As she begins to uncover the truths of the life that she's found herself in, the gravity of her failing reality weighs heavily on her psychological identity and the reliability of her sanity is called into question.",
            originalTitle= "Parallax",
            genres= "Science Fiction, Thriller",
            releaseDate= "2020-07-10",
            runtime= "0",
            tagline= "",
            status= "Released",
            voteAverage= "1.0",
            voteCount= "1",
            posterPath= "/nRYx4zpDhGuM85ESFbAhzmAWoEn.jpg",
            backdropPath= "/kFlMEOyXqaeZzFLSZrStYx1TRq3.jpg"
        ),
        Movie(
            id= "514847",
            title= "The Hunt",
            overview= "Twelve strangers wake up in a clearing. They don't know where they are—or how they got there. In the shadow of a dark internet conspiracy theory, ruthless elitists gather at a remote location to hunt humans for sport. But their master plan is about to be derailed when one of the hunted turns the tables on her pursuers.",
            originalTitle= "The Hunt",
            genres= "Action, Thriller, Horror",
            releaseDate= "2020-03-11",
            runtime= "90",
            tagline= "The Ultimate Human Hunting Experience",
            status= "Released",
            voteAverage= "6.7",
            voteCount= "1064",
            posterPath= "/wxPhn4ef1EAo5njxwBkAEVrlJJG.jpg",
            backdropPath= "/naXUDz0VGK7aaPlEpsuYW8kNVsr.jpg"
        ),
        Movie(
            id= "486589",
            title= "Red Shoes and the Seven Dwarfs",
            overview= "Princes who have been turned into Dwarfs seek the red shoes of a lady in order to break the spell, although it will not be easy.",
            originalTitle= "Red Shoes and the Seven Dwarfs",
            genres= "Animation, Romance, Family",
            releaseDate= "2019-07-25",
            runtime= "92",
            tagline= "",
            status= "Released",
            voteAverage= "7.0",
            voteCount= "207",
            posterPath= "/MBiKqTsouYqAACLYNDadsjhhC0.jpg",
            backdropPath= "/bga3i5jcejBekr2FCGJga1fYCh.jpg"
        ),
        Movie(
            id= "603",
            title= "The Matrix",
            overview= "Set in the 22nd century, The Matrix tells the story of a computer hacker who joins a group of underground insurgents fighting the vast and powerful computers who now rule the earth.",
            originalTitle= "The Matrix",
            genres= "Action, Science Fiction",
            releaseDate= "1999-03-30",
            runtime= "136",
            status= "Released",
            tagline= "Welcome to the Real World.",
            voteAverage= "8.1",
            voteCount= "17363",
            posterPath= "/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg",
            backdropPath= "/ByDf0zjLSumz1MP1cDEo2JWVtU.jpg"
        ),
        Movie(
            id= "502425",
            title= "Escape From Pretoria",
            overview= "South Africa, 1978. Tim Jenkin and Stephen Lee, two white political activists from the African National Congress imprisoned by the apartheid regime, put a plan in motion to escape from the infamous Pretoria Prison.",
            originalTitle= "Escape From Pretoria",
            genres= "Drama, History, Thriller",
            releaseDate= "2020-03-06",
            runtime= "102",
            tagline= "Survival is key",
            status= "Released",
            voteAverage= "7.2",
            voteCount= "283",
            posterPath= "/8GGS0jkFFCnmdStvZED6NL6V7gd.jpg",
            backdropPath= "/kolkVKNZSjhZGHwcrFU36Watpke.jpg"
        ),
        Movie(
            id= "662708",
            title= "Pokémon the Movie: Coco",
            overview= "The new film's story is set in Okoya Forest, a Pokémon paradise protected by strict rules that forbid outsiders from setting foot inside. The film centers on Coco, a boy who was raised by Pokémon and also considers himself as one, treating the Mythical Pokémon Zarude as his father. Ash and Pikachu encounter Coco during an adventure.",
            originalTitle= "劇場版ポケットモンスター ココ",
            genres= "Adventure, Animation",
            releaseDate= "2020-07-10",
            runtime= "0",
            tagline= "",
            status= "Released",
            voteAverage= "2.0",
            voteCount= "1",
            posterPath= "/gAp97LxqHTldd6sWeIq60Ft6kEB.jpg",
            backdropPath= "/4KpNHvQIjyg1YFovRAoUXoFrGnR.jpg"
        ),
        Movie(
            id= "592350",
            title ="My Hero Academia: Heroes Rising",
            overview= "Class 1-A visits Nabu Island where they finally get to do some real hero work. The place is so peaceful that it's more like a vacation … until they're attacked by a villain with an unfathomable Quirk! His power is eerily familiar, and it looks like Shigaraki had a hand in the plan. But with All Might retired and citizens' lives on the line, there's no time for questions. Deku and his friends are the next generation of heroes, and they're the island's only hope.",
            originalTitle = "僕のヒーローアカデミア THE MOVIE ヒーローズ：ライジング",
            genres= "Animation, Action",
            releaseDate= "2019-12-20",
            runtime= "104",
            tagline ="",
            status ="Released",
            voteAverage ="8.8",
            voteCount= "110",
            posterPath= "/zGVbrulkupqpbwgiNedkJPyQum4.jpg",
            backdropPath ="/9guoVF7zayiiUq5ulKQpt375VIy.jpg"
        ),
        Movie(
            id= "526973",
            title= "Target Number One",
            overview= "Ex heroin junkie, Daniel Léger, gets involved in a drug deal with the wrong people for the wrong reasons. When the deal goes sour, Daniel gets thrown into a Thai prison and slapped with a 100-year sentence. While he tries to survive his Bangkok incarceration, the news of his conviction captures the attention of Globe and Mail journalist Victor Malarek, who decides to go after the shady undercover cops responsible for wrongly accusing Daniel.",
            originalTitle= "Target Number One",
            genres= "Crime, Thriller",
            releaseDate= "2020-07-10",
            runtime= "0",
            status= "Released",
            tagline= "",
            voteAverage= "2.0",
            voteCount= "1",
            posterPath= "/npOZUVjSUJbL3WkL9jZBZ6gwURk.jpg",
            backdropPath= "/4NQFjYust0K9WdGnXF1a4FDiDap.jpg"
        ),
        Movie(
            id= "522444",
            title= "Black Water: Abyss",
            overview= "An adventure-loving couple convince their friends to explore a remote, uncharted cave system in the forests of Northern Australia. With a tropical storm approaching, they abseil into the mouth of the cave, but when the caves start to flood, tensions rise as oxygen levels fall and the friends find themselves trapped. Unknown to them, the storm has also brought in a pack of dangerous and hungry crocodiles.",
            originalTitle= "Black Water: Abyss",
            genres= "Horror, Thriller, Adventure",
            releaseDate= "2020-07-09",
            runtime= "0",
            tagline= "Descend into fear",
            status= "Released",
            voteAverage= "5.2",
            voteCount= "5",
            posterPath= "/9uY8zhNeDk77Mwuy2DP4zjS3YTq.jpg",
            backdropPath= "/81Aux0tOfORrWOJeMDx0m3VIB95.jpg"
        ),
        Movie(
            id= "522098",
            title= "Babyteeth",
            overview= "A terminally ill teen upsets her parents when she falls in love with a small-time drug dealer.",
            originalTitle= "Babyteeth",
            genres= "Drama, Comedy",
            releaseDate= "2020-06-18",
            runtime= "118",
            tagline= "",
            status= "Released",
            voteAverage= "5.5",
            voteCount= "25",
            posterPath= "/aINpljdt3VVMrCLtJW4BektwYOp.jpg",
            backdropPath= "/cjAirCV9TyTQcp7mFNRnvgkoVFV.jpg"
        )

    )

    val tvShows = arrayOf(
        TvShow(
            "48866",
            "The 100",
            "100 years in the future, when the Earth has been abandoned due to radioactivity, the last surviving humans live on an ark orbiting the planet — but the ark won't last forever. So the repressive regime picks 100 expendable juvenile delinquents to send down to Earth to see if the planet is still habitable.",
            "The 100",
            "Drama, Action & Adventure, Sci-Fi & Fantasy",
            "2014-03-19",
            listOf("43"),
            true,
            "Returning Series",
            "7.5",
            "3403",
            "/wcaDIAG1QdXQLRaj4vC1EFdBT2.jpg",
            "/hTExot1sfn7dHZjGrk0Aiwpntxt.jpg",
            "93",
            "7"
        ),
        TvShow(
            "1403",
            "Marvel's Agents of S.H.I.E.L.D.",
            "Agent Phil Coulson of S.H.I.E.L.D. (Strategic Homeland Intervention, Enforcement and Logistics Division) puts together a team of agents to investigate the new, the strange and the unknown around the globe, protecting the ordinary from the extraordinary.",
            "Marvel's Agents of S.H.I.E.L.D.",
            "Drama, Sci-Fi & Fantasy, Action & Adventure",
            "2013-09-24",
            listOf("43"),
            true,
            "Returning Series",
            "7.1",
            "1820",
            "/gHUCCMy1vvj58tzE3dZqeC9SXus.jpg",
            "/mUCV0W6TaAk8UWA5yAmqCywC63F.jpg",
            "136",
            "7"
        ),
        TvShow(
            "1433",
            "American Dad!",
            "The series focuses on an eccentric motley crew that is the Smith family and their three housemates: Father, husband, and breadwinner Stan Smith; his better half housewife, Francine Smith; their college-aged daughter, Hayley Smith; and their high-school-aged son, Steve Smith. Outside of the Smith family, there are three additional main characters, including Hayley's boyfriend turned husband, Jeff Fischer; the family's man-in-a-goldfish-body pet, Klaus; and most notably the family's zany alien, Roger, who is \"full of masquerades, brazenness, and shocking antics.\"",
            "American Dad!",
            "Animation, Comedy",
            "2005-02-06",
            listOf("22"),
            true,
            "Returning Series",
            "6.4",
            "925",
            "/1aklTBd36LFiFNroOSiherLvLdu.jpg",
            "/2OeS0YPFpqCmi7SA5W6aOPIChc3.jpg",
            "293",
            "17"
        ),
        TvShow(
            "2661",
            "Kamen Rider",
            "A Japanese anthology series centered around a man who transforms into a bug-themed superhero.",
            "仮面ライダ",
            "Action & Adventure, Drama, Sci-Fi & Fantasy",
            "1971-04-03",
            listOf("30"),
            true,
            "Returning Series",
            "5.3",
            "40",
            "/o57T19zgZakEpre3d9ddy1UZonp.jpg",
            "/73vNiJs4j33A8Oieu0DhSnPTJj8.jpg",
            "1455",
            "30"
        ),
        TvShow(
            "60572",
            "Pokémon",
            "Join Ash Ketchum, accompanied by his partner Pikachu, as he travels through many regions, meets new friends and faces new challenges on his quest to become a Pokémon Master.",
            "ポケモン",
            "Animation, Action & Adventure, Sci-Fi & Fantasy, Kids",
            "1997-04-01",
            listOf("22"),
            true,
            "Returning Series",
            "6.8",
            "344",
            "/2AoqUTKKN4kjNe1K0kIPwiItHwv.jpg",
            "/tvjCdVRkaaab2ezM9BctkAOXeyW.jpg",
            "1119",
            "23"
        ),
        TvShow(
            "4656",
            "WWE Raw",
            "WWE Raw is a professional wrestling television program that currently airs live on Monday evenings on the USA Network in the United States. The show debuted on January 11, 1993. WWE Raw moved from the USA Network to TNN in September, 2000 and then to Spike TV in August, 2003 when TNN was rebranded. On October 3, 2005 WWE Raw returned to the USA Network.\\n\\nSince its first episode, WWE Raw has broadcast live from 203 different arenas in 169 cities and towns in ten different nations. As of the show's 1,000th episode, airing on July 23, 2012, WWE Raw has become a three-hour broadcast from two-hours, a format that had previously been reserved for special episodes.",
            "WWE Raw",
            "Reality",
            "1993-01-11",
            listOf("130"),
            true,
            "Returning Series",
            "6.2",
            "174",
            "/2bZ5c9sHbzApWVIsUoWztg43EgB.jpg",
            "/l6ci9v4XC6DCTlZG8NiufRBx3kG.jpg",
            "1422",
            "28"
        ),
        TvShow(
            "79501",
            "Doom Patrol",
            "The Doom Patrol’s members each suffered horrible accidents that gave them superhuman abilities — but also left them scarred and disfigured. Traumatized and downtrodden, the team found purpose through The Chief, who brought them together to investigate the weirdest phenomena in existence — and to protect Earth from what they find.",
            "Doom Patrol",
            "Action & Adventure, Sci-Fi & Fantasy",
            "2019-02-15",
            listOf("49"),
            true,
            "Returning Series",
            "7.3",
            "482",
            "/drlfSCIlMKrEeMPhi8pqY4xGxj.jpg",
            "/rqHL4HsLCix9H6vhCwAuSOge0NS.jpg",
            "23",
            "2"
        ),
        TvShow(
            "502",
            "Sesame Street",
            "On a special inner city street, the inhabitants—human and muppet—teach preschoolers basic educational and social concepts using comedy, cartoons, games, and songs.",
            "Sesame Street",
            "Comedy, Kids",
            "1969-11-10",
            listOf("54","60"),
            true,
            "Returning Series",
            "7.2",
            "125",
            "/xNWfDneXNj4EJjqFR1gFbM3wbnc.jpg",
            "/rYlCELMEo1IFfjJB6EP1ket8gM.jpg",
            "2899",
            "50"
        ),
        TvShow(
            "80986",
            "Stargirl",
            "Courtney Whitmore, a smart, athletic and above all else kind girl, discovers her step-father has a secret: he used to be the sidekick to a superhero. \"Borrowing\" the long-lost hero’s cosmic staff, she becomes the unlikely inspiration for an entirely new generation of superheroes.",
            "Stargirl",
            "Crime, Drama, Action & Adventure, Sci-Fi & Fantasy",
            "2020-05-18",
            listOf("43"),
            true,
            "Returning Series",
            "8",
            "411",
            "/sWSGc3Bb7aCTOPvAIkkhqI7ae9H.jpg",
            "/b5lKppEquuQWm6fTjGcu2g8FJgs.jpg",
            "13",
            "1"
        ),
        TvShow(
            "45253",
            "Super Sentai",
            "The Super Sentai Series is the name given to the long-running Japanese superhero team genre of shows produced by Toei Co., Ltd., Toei Agency and Bandai, and aired by TV Asahi. The shows are of the tokusatsu genre, featuring live action characters and colorful special effects, and are aimed mainly at children. The Super Sentai Series is one of the most prominent tokusatsu productions in Japan, alongside the Ultra Series and the Kamen Rider Series, which it currently airs alongside in the Super Hero Time programming block on Sundays. Outside Japan, the Super Sentai Series are best known as the source material for the Power Rangers franchise.",
            "スーパー戦隊シリーズ",
            "Action & Adventure, Sci-Fi & Fantasy",
            "1975-04-05",
            listOf("30"),
            true,
            "Returning Series",
            "4.1",
            "87",
            "/tDq8av51oHR8YWgkiHQ2oeRO5iL.jpg",
            "/dHlKH9vTumj7tPBeYVWGzI7UJ9I.jpg",
            "2181",
            "44"
        ),
        TvShow(
            "79680",
            "Snowpiercer",
            "Set more than seven years after the world has become a frozen wasteland, the remnants of humanity inhabit a gigantic, perpetually-moving train that circles the globe as class warfare, social injustice and the politics of survival play out.",
            "Snowpiercer",
            "Sci-Fi & Fantasy",
            "2020-05-17",
            listOf("50"),
            true,
            "Returning Series",
            "7.6",
            "219",
            "/n6UNHZoiYj81abwmG38HbNjflDx.jpg",
            "/dJBKKbrQIqcQ9EUbdM48dM8mso6.jpg",
            "10",
            "1"
        ),
        TvShow(
            "1554",
            "QI",
            "Comedy quiz show full of quirky facts, in which contestants are rewarded more if their answers are 'quite interesting'.",
            "QI",
            "Comedy, Talk",
            "2003-09-11",
            listOf("30"),
            true,
            "Returning Series",
            "8.1",
            "128",
            "/hieAAv1MVYzRuX12ttVmlq7kGn9.jpg",
            "/uA62IypAzFWNloocQcsUfvp4Jh.jpg",
            "283",
            "18"
        ),
        TvShow(
            "65942",
            "Re:ZERO -Starting Life in Another World-",
            "Natsuki Subaru, an ordinary high school  student, is on his way home from the convenience store when he finds  himself transported to another world. As he's lost and confused in a new  world where he doesn't even know left from right, the only person to  reach out to him was a beautiful girl with silver hair. Determined to  repay her somehow for saving him from his own despair, Subaru agrees to  help the girl find something she's looking for.",
            "Re：ゼロから始める異世界生活",
            "Animation, Comedy, Drama, Action & Adventure, Sci-Fi & Fantasy",
            "2016-04-04",
            listOf("25"),
            true,
            "Returning Series",
            "7.5",
            "108",
            "/5DZa4aDH5MZGcZDf8ouTxm2kH2Y.jpg",
            "/ai8bVS8Suvu4ErBhmgBvtESirBY.jpg",
            "27",
            "2"
        ),
        TvShow(
            "103783",
            "Little Voice",
            "A love letter to the diverse musicality of New York and an exploration the universal journey of finding your authentic voice in your early 20s — and the courage to use it.",
            "Little Voice",
            "Drama, Comedy",
            "2020-07-10",
            listOf("30"),
            true,
            "Returning Series",
            "7.5",
            "4",
            "/vxzWAyNw7T7r7a6aQdPe2bahMPh.jpg",
            "/wRDOlYGIEqeupAaggkMfjiuib1j.jpg",
            "5",
            "1"
        ),
        TvShow(
            "71146",
            "Condor",
            "Young CIA analyst Joe Turner has his idealism tested when he learns that the CIA has been using an algorithm he developed to spy on American citizens, leading the organization to a terrorist plot that threatens the lives of millions.  Inspired by Sydney Pollack’s 1975 political thriller Three Days of the Condor.",
            "Condor",
            "Drama",
            "2018-06-06",
            listOf("53"),
            true,
            "Returning Series",
            "6.5",
            "76",
            "/28cIK70tN2t4gPTV8CBQZED1H2G.jpg",
            "/fc9ebsTmVCvv6jjD2qT7rWazaej.jpg",
            "18",
            "2"
        ),
        TvShow(
            "73586",
            "Yellowstone",
            "Follow the violent world of the Dutton family, who controls the largest contiguous ranch in the United States. Led by their patriarch John Dutton, the family defends their property against constant attack by land developers, an Indian reservation, and America’s first National Park.",
            "Yellowstone",
            "Drama, Western",
            "2018-06-20",
            listOf("42"),
            true,
            "Returning Series",
            "7.8",
            "108",
            "/43nVQqVsrshaOx9GfJq6JstsfCX.jpg",
            "/oBilGalyrQJTtDuYIljRQGNXXb8.jpg",
            "24",
            "3"
        ),
        TvShow(
            "31991",
            "WWE NXT",
            "Wrestlers will portray heroes or villains as they follow a series of events that build tension and culminate in a wrestling match or series of matches.",
            "WWE NXT",
            "Action & Adventure, Drama",
            "2010-02-23",
            listOf("120"),
            true,
            "Returning Series",
            "6.2",
            "45",
            "/yh6cpWfIaiNbZDlqTjjzv7OSooV.jpg",
            "/oO36eZ1AX3SikQ6FDpQ7df4T5IT.jpg",
            "555",
            "14"
        ),
        TvShow(
            "96316",
            "Rent-a-Girlfriend",
            "In today's Japan, \"rental\" services can deliver an afternoon with a \"friend,\" a \"parent,\" even a fake girlfriend! Kinoshita Kazuya is a 20-year-old failure of a college student. He managed to kiss his girlfriend once, but was dumped after a month.  Completely spiteful, Kazuya gets just desperate enough to give it a try. But he quickly discovers how complicated it can be to \"rent\" an emotional connection... and his new \"girlfriend\", Mizuhara Chizuru, who's trying to keep her side hustle secret, will panic when she finds out her real life and Kazuya's are intertwined in surprising ways! A reckless rom-com filled with love and excitement is about to begin!",
            "彼女、お借りします",
            "Animation, Comedy",
            "2020-07-10",
            listOf("24"),
            true,
            "Returning Series",
            "5",
            "2",
            "/lZtfm5fLdwiMusZqoY9vf8Rjtz1.jpg",
            "/yozfbzwLhGe81YKTDoNDRdJrIuC.jpg",
            "12",
            "1"
        ),
        TvShow(
            "98986",
            "Uzaki-chan Wants to Hang Out!",
            "University student Shinichi Sakurai is comfortable being an introverted loner and doesn’t care what others think. Buxom underclassmen Hana Uzaki doesn’t understand this one bit. A tornado of joy, she’s taken it upon herself to make him more social. Starting to enjoy her company, he’d concede that they’re friends. Can it be possible to have as much fun with another person as he would by himself?",
            "宇崎ちゃんは遊びたい！",
            "Animation, Comedy",
            "2020-07-10",
            listOf("24"),
            true,
            "Returning Series",
            "9",
            "2",
            "/4EBxanQHK1fSYsdeRVpBAGeknFN.jpg",
            "/4XZGGgOTj7PcWfpF7kSnVHUE49g.jpg",
            "12",
            "1"
        ),
        TvShow(
            "85853",
            "Perry Mason",
            "Set in 1932 Los Angeles, the series focuses on the origin story of famed defense lawyer Perry Mason. Living check-to-check as a low-rent private investigator, Mason is haunted by his wartime experiences in France and suffering the effects of a broken marriage. L.A. is booming while the rest of the country recovers from the Great Depression — but a kidnapping gone very wrong leads to Mason exposing a fractured city as he uncovers the truth of the crime.",
            "Perry Mason",
            "Crime, Drama, Mystery",
            "2020-06-21",
            listOf("60"),
            true,
            "Returning Series",
            "7.3",
            "52",
            "/gPBf35AqvXHvKEpDHaQ4D9xXxeX.jpg",
            "/jGwCKq2EbQbsgNTBM2NoEzFHRdh.jpg",
            "8",
            "1"
        )
    )

}